### ISSUE TITLE
Single Containment reference is not supported

### ISSUE THREAD

**Issue by AtanasM98** [LionWeb-io/lionweb-java#111] opened 2023-11-06 14:49 UTC
Trying to export a model that uses a meta model that has a reference set as a single containment(Lower & Upper bound=1) throws and unsupported exception. [Example of code with this problem.](https://github.com/LionWeb-io/property-demo/tree/atanas/single-containment-bug)
[Line in EMFModelExporter where problem occurs.](https://github.com/LionWeb-io/lionweb-java/blob/f6a67bdd1a7dd54c032dedb9a95d0458cdc4ad25/emf/src/main/java/io/lionweb/lioncore/java/emf/EMFModelExporter.java#L67)
## How to reproduce bug:
In property-demo repository execute
`./gradlew xtend-generators:emf-generator:run`

**Comment by ftomassetti** [comment] 2023-11-06 16:01
How urgent is this? Do you need solved for LangDev?

**Comment by ftomassetti** [comment] 2023-11-07 12:07
I think I have a fix for this, but to test it could you share with me the \example1-exported.lm.json file referred in the linked repo?

**Comment by AtanasM98** [comment] 2023-11-07 15:34
Hello sorry. I commited the [lm file in the repo.](https://github.com/LionWeb-io/property-demo/blob/atanas/xtend-generators/properties-parser/example1-exported.lm.json)

**Comment by ftomassetti** [comment] 2023-11-07 17:09
I cannot reproduce the problem, but given we are on a deadline I will open the PR with the fix anyway

**Comment by ftomassetti** [comment] 2023-11-08 11:46
I have now a test for this, but my test is currently not passing even after my fix for a problem I cannot figure out. At some point this line is called with eClass=Property:

```
EObject eObject = eClass.getEPackage().getEFactoryInstance().create(eClass);
```

Given that Property implements INamed, this code cause the create method to be invoked with eClass=INamed:

```
  public EObject create(EClass eClass) 
  {
    if (getEPackage() != eClass.getEPackage() || eClass.isAbstract())
    {
      throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }

    for (List<EClass> eSuperTypes = eClass.getESuperTypes(); !eSuperTypes.isEmpty(); )
    {
      EClass eSuperType = eSuperTypes.get(0);
      if (eSuperType.getInstanceClass() != null)
      {
        EObject result = eSuperType.getEPackage().getEFactoryInstance().create(eSuperType);
        ((InternalEObject)result).eSetClass(eClass);
        return result;
      }
      eSuperTypes = eSuperType.getESuperTypes();
    }

    return basicCreate(eClass);
  }
 ```
 
 And the BuiltinsFactoryImpl.create method looks like this:
 ```
 	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EObject create(EClass eClass)
	{
		switch (eClass.getClassifierID())
		{
			default:
				throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
		}
	}
```

So the test fails. Now, I suppose that given INamed is an interface the create method should never be called with eClass=INamed, so I am not sure why is this happening. Is because Property should extend some basic class and that should be the _first_ supertype? Maybe @enikao knows the answer to this

**Comment by ftomassetti** [comment] 2023-11-08 11:53
Well, I will answer myself. Adding these lines seem to help:
```
  private void populateEClassFromConcept(Concept concept) {
    EClass eClass = (EClass) conceptsToEClassesMapping.getCorrespondingEClass(concept);

    if (concept.getExtendedConcept() != null) {
      EClass superEClass =
          (EClass) conceptsToEClassesMapping.getCorrespondingEClass(concept.getExtendedConcept());
      eClass.getESuperTypes().add(superEClass);
    } else {
      // this is new
      eClass.getESuperTypes().add(EcorePackage.eINSTANCE.getEObject());
    }
```

**Closed** 2023-11-08 15:03 UTC
